spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/manager?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 2777679537@qq.com
    password: uidhrhpdlhgvdhfg
    nickname: 管理员
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
server:
  port: 9999
